### ISSUE TITLE
Template 1.5 Server Navi

### ISSUE THREAD

**Issue by 65DirtyHarry** [DZCP-Community/DZCP-1.6-OLD#139]
MoinMoin

Im Template 1.5 von der 1.7er sind kleine Grafik Fehler.
![dzcp_1_7_template_1_5_fehler](https://cloud.githubusercontent.com/assets/6206060/5736453/4fad6662-9bd6-11e4-9ac1-0bbeb4468a36.png)

**Comment by hammermaps** [comment]
Ein Fall für unsere HTML Jungs xD, Koma / Acecom :)

**Comment by acecom** [comment]
folgende file aus den template bitte löschen
inc / _templates_ / version1.5 / menu / nav_server.html
